"""

Revision ID: d825c9f4026a
Revises: 1e03dedc9003
Create Date: 2025-07-30 17:16:17.887364

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d825c9f4026a"
down_revision: Union[str, Sequence[str], None] = "1e03dedc9003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

gender_enum = sa.Enum(
    "MALE",
    "FEMALE",
    name="gender",
)

zodiac_enum = sa.Enum(
    "ARIES",
    "TAURUS",
    "GEMINI",
    "CANCER",
    "LEO",
    "VIRGO",
    "LIBRA",
    "SCORPIO",
    "SAGITTARIUS",
    "CAPRICORN",
    "AQUARIUS",
    "PISCES",
    name="zodiacs",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    gender_enum.create(op.get_bind(), checkfirst=True)
    zodiac_enum.create(op.get_bind(), checkfirst=True)

    op.drop_table("refresh_tokens")
    op.add_column("users", sa.Column("name", sa.String(), nullable=False))
    op.add_column("users", sa.Column("age", sa.Integer(), nullable=False))
    op.add_column("users", sa.Column("gender", gender_enum, nullable=False))
    op.add_column("users", sa.Column("zodiac", zodiac_enum, nullable=False))
    op.add_column("users", sa.Column("height", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("weight", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("description", sa.JSON(), nullable=True))
    op.add_column("users", sa.Column("profile_photo_url", sa.String(), nullable=True))
    op.add_column("users", sa.Column("contacts", sa.String(), nullable=True))
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_column("users", "is_active")
    op.drop_column("users", "is_verified")
    op.drop_column("users", "email")
    op.drop_column("users", "is_superuser")
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "hashed_password",
            sa.VARCHAR(length=1024),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column("is_superuser", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users",
        sa.Column("email", sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users",
        sa.Column("is_verified", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.drop_column("users", "contacts")
    op.drop_column("users", "profile_photo_url")
    op.drop_column("users", "description")
    op.drop_column("users", "weight")
    op.drop_column("users", "height")
    op.drop_column("users", "zodiac")
    op.drop_column("users", "gender")
    op.drop_column("users", "age")
    op.drop_column("users", "name")
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("token", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("refresh_tokens_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("refresh_tokens_pkey")),
        sa.UniqueConstraint(
            "token",
            name=op.f("refresh_tokens_token_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )

    gender_enum.drop(op.get_bind(), checkfirst=True)
    zodiac_enum.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
